In [1]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os

load_dotenv()

url = os.getenv("baseUrl")

params = {"companyId":"545277"}

headers = {
	"x-rapidapi-key": os.getenv("RAPIDAPI_KEY"),
	"x-rapidapi-host": os.getenv("RAPIDAPI_HOST")
}

response = requests.get(url, headers=headers, params=params)

data = response.json().get('data', []).get('employerReviewsRG', []).get('reviews', [])

df = pd.DataFrame(data)
df.head()

,__typename,advice,cons,countHelpful,employer,employerResponses,featured,hasEmployerResponse,isCurrentJob,jobTitle,...,ratingCompensationAndBenefits,ratingCultureAndValues,ratingDiversityAndInclusion,ratingOverall,ratingRecommendToFriend,ratingSeniorLeadership,ratingWorkLifeBalance,reviewDateTime,reviewId,summary
0,EmployerReviewRG,"Stop micromanaging everything, train people pr...","Management control is on another level, microm...",3,"{'id': 545277, 'shortName': 'Susi Air', 'squar...",[],False,False,False,{'text': 'Pilot'},...,1.0,1,4,2,NEGATIVE,1.0,1.0,2024-12-24T20:55:31.283,93885460,Wrkg with untr. newbs low sal. bad vibe at wrk...
1,EmployerReviewRG,"Unfortunately, no matter how good the advice i...","Without realizing it, this office hires a lot ...",6,"{'id': 545277, 'shortName': 'Susi Air', 'squar...",[],False,False,False,{'text': 'Management Trainee'},...,1.0,1,1,1,NEGATIVE,1.0,1.0,2024-12-01T23:43:31.583,93312284,Maid Covered As Management Trainee
2,EmployerReviewRG,"Advice for management is ""PLEASE FIX YOUR ATTI...",1. Never get appreciation. even we did a great...,5,"{'id': 545277, 'shortName': 'Susi Air', 'squar...",[],False,False,True,{'text': 'Administrator'},...,1.0,1,1,2,NEGATIVE,1.0,1.0,2024-12-06T19:47:12.643,93471008,Not Good for the mental health
3,EmployerReviewRG,Listen to your employees,The French manager’s poor treatment of employe...,2,"{'id': 545277, 'shortName': 'Susi Air', 'squar...",[],False,False,False,"{'text': 'Pilot, First Officer'}",...,3.0,3,4,3,POSITIVE,3.0,4.0,2024-12-04T14:45:23.583,93405277,Ok to build up hours
4,EmployerReviewRG,None,it's far from the city,0,"{'id': 545277, 'shortName': 'Susi Air', 'squar...",[],False,False,False,{'text': 'Management Trainee'},...,4.0,4,5,4,None,4.0,4.0,2024-11-25T23:24:54.403,93172436,Good Opportunity

In [2]:
df.to_csv('glassdoor_review.csv', index=False)